### PR TITLE
Error handling for RenderDoc module import

### PR DESCRIPTION
**Pull request by jokumo**
### New error messages on the GUI
I added more specific error messages to appear on the GUI when it's not possible to import the RenderDoc module. 
And there's a new "unknown Error occurred"-message which as of now most probably never will get displayed because any error (except the new RenderDoc errors) will result in a returncode == 1. As of now this will result in a "invalid RDC file"-error, which isn't always correct (and may mislead the user).
I suggest (and might do it myself) to implement an extra returncode to make sure the "invalid RDC file"-error only appears if it's really about an invalid RDC file. 

### More details on the console level
It now will give more details on the console level when something doesn't work as expected while importing RenderDoc module.
- if the module wasn't found it will print the searched paths (sys.path)
- if the module was found but an exception got raised while importing it, it will print the following information on the console:
  - Operating system (sys.platform)
  - Python version used by the script (sys.version)
  - Module name
  - Module location/path
  - Error message of the exception

### CODE REVIEW

**Comment by eliemichel** [comment]
Thanks! Could you revert the change of indentation style? Not that I am particularily attached to it but it makes the diff unreadable!

**Comment by jokumo** [comment]
If it's just about the diff, there's a workaround. For pull requests there's a checkbox "Hide whitespace changes" (Files changed-Tab -> Settings-gearwheel)
GitHub ignore whitespaces_LI (2)
If I remember right on the command line you can use the -w option. Same works for comparing two files or branches on github.com by adding a "?w=1" to the end of the URL. (If there is already a ? in the url it must be written with a & instead ( "&w=1" ))
GitHub ignore whitespaces W-Option

But I agree, this can be annoying. Especially if a code gets messed up with two different indentation styles and the editor/IDE doesn't display them the same way.
I will try to adjust my editor for the next time.

**Comment by jokumo** [comment]
Done. It was not the indentation style but the end-of-line character. I just realized that it is easy to spot the difference by eye: Indentation incompatibility would show only lines with indentation while EOL-character incompatibility just shows every line. 
In Sublime 3 I had to change it from Windows to Unix. Not sure which one it is now, but seems to be the same now.

But there's still a slight advantage if you use the "hide whitespace changes"-option. You can see it on line 27 of google_maps_rd.py: The only change in this line is the indentation, ignoring whitespaces will threat the line as unchanged, otherwise you have to manually spot it as the same line.

**Comment by jokumo** [comment]
I just saw that I removed the success-boolean logic because I thought it is redundant. Was this ok or did I missed something?

**Comment by eliemichel** [comment]
> For pull requests there's a checkbox "Hide whitespace changes"

Didn't know this, thanks!

> I just realized that it is easy to spot the difference by eye: Indentation incompatibility would diff only lines with indentation while EOL-character incompatibility just shows any line as different.
In Sublime 3 I had to change it from Windows to Unix.

There is an option in git on windows to ask it to automatically convert line endings upon commit to avoid this kind of issue. ;)

> I just saw that I removed the success-boolean logic because I thought it is redundant. Was this ok or did I miss something?

Seems redundant indeed. I don't remember how we ended up like so tbh so let's remove it. ^^

Thanks overall for improving clarity of the error messages, you're doing a great job at alleviating the load of "Import of RDC failed" errors that is a bit overflowing my notifications on all sorts of social media..

**Comment by jokumo** [comment]
> There is an option in git on windows to ask it to automatically convert line endings upon commit to avoid this kind of issue. ;)
Oh, I wasn't aware of this, thanks. :)

**Pull request merged**
